openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8081
    description: root url
paths:
  /service-provider:
    post:
      tags:
        - service provider
      summary: Add a new Service Provider
      description: Add a new Service Provider to provide review for/against
      operationId: addServiceProvider
      requestBody:
        description: Create a new Service Provider
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestSpDto'
        required: true
      responses:
        '201':
          description: Service Provider successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSpDto'

  /service-provider/{id}:
    get:
      tags:
        - service provider
      operationId: retrieveServiceProvider
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseSpDto'
    put:
      tags:
        - service provider
      operationId: updateServiceProvider
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestSpDto'
        required: true
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseSpDto'
    delete:
      tags:
        - service provider
      operationId: deleteServiceProvider
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: NO-CONTENT
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseSpDto'
components:
  schemas:
    RequestSpDto:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        address:
          type: string
        phoneNo:
          type: string
        category:
          type: string
    ResponseSpDto:
      type: object
      properties:
        spId:
          type: string
        email:
          type: string
        name:
          type: string
        address:
          type: string
        phoneNo:
          type: string
        category:
          type: string
